project_id = "wccsjoaqjnevdhfsjewk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://clt-facil-calculadoras.lovable.app"]
jwt_expiry = 3600

[functions]
enabled = true
port = 54329

[functions.checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.get-price]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54330

[analytics]
enabled = false